name: ci-fullstack-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: 
      - main

#Use a matrix strategy to use Node.js versions 20 
jobs:
  install-build-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
    steps:
      # Reference a specific commit
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      # Reference the major version of a release
      - uses: actions/checkout@v4 
      # Reference a branch
      - uses: actions/checkout@main

        with:
          node-version: ${{ matrix.node-version }}

      # Install the dependencies.
      - run: cd backend && npm install

      # Run the tests.
      - run: cd backend && npm test

      # Run the linter.
      - run: cd backend && npm run lint

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

  stage:
    runs-on: ubuntu-latest
    needs: install-build-test
    environment:
      name: staging

    steps:
      # Simulate a Deployment
      - name: Deploy to Staging
        run: |
         echo "Deployed to staging environment"

  production:
    runs-on: ubuntu-latest
    needs: stage
    environment:
      name: production

    steps:
      # Simulate a Deployment
      - name: Deploy to Production
        run: |
         echo "Deployed to production environment"